import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { StudentProvider } from "./context/StudentContext";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
});

export const metadata = {
  title: "GradeUFOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} min-h-screen`} suppressHydrationWarning={true}>
        <ThemeRegistry>
          <StudentProvider>
            <header className="flex w-full h-16 items-center justify-center text-lg fixed top-0 z-10 bg-primary text-white">
              GradeUFOP
            </header>
            <main className="py-16">
              {children}
            </main>
          </StudentProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
